### ISSUE TITLE
Низкое качества снимка

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#125]
Снимали с iPad2 фотка получилась всего 26 КБ:
https://s3-eu-west-1.amazonaws.com/gkgradus/STMUncashingPicture/2014/11/19/DD28E1E7-D4D1-4341-B7C3-5D7630B2DC1A.jpg

**Comment by gogbajbobo** [comment]
Cделал сеттинг appSettings / jpgQuality, значения float от 0.0 (наибольшее сжатие) до 1.0 (наилучшее качество). По умолчанию 0.0 — как и было раньше.

Результаты сжатия одной и той же картинки:
jpgQuality / imageSize
0.0 / 128528
0.5 / 352962
0.8 / 649878
1.0 / 1745498
