### ISSUE TITLE
Писать в ClientData про запрет геолокации

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#168]
Если юзера надо отслеживать, а он запретил трекинг, то надо записать что-то в какое-то поле новое

**Comment by gogbajbobo** [comment]
новое поле в stc.ClientData — locationServiceStatus, строковое, возможные значения: https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/c/tdef/CLAuthorizationStatus

**Comment by alevinru** [comment]
Походу оно туда не сразу записывается. Т.е. пользователь поставил обновление, запустил прогу, сказал "Да" геолокации. Мне в stc.ClientData дата пришло что билд поменялся, а locationServiceStatus все еще notDetermined. Наверное, придет при следующем запуске когда прога сдохнет.

**Comment by gogbajbobo** [comment]
клиентДата должна обновиться при следующей её проверке, а она производится перед началом синхронизации.
проверю.

**Comment by alevinru** [comment]
Вроде да, обновилось при следующем. Хоца сразу, конечно

**Comment by gogbajbobo** [comment]
Ну оно сразу и есть, каждый раз перед тем как слать данные с клиента, оно тамо проверяет, есть ли изменения в данных для клиентДаты, если есть то прикручивает их, и только потом всё шлёт.
Если в данных пришла клиентДата и там notDetermined, то значит так оно на момент перед отправкой данных и было.
Вроде всё именно так должно работать.

**Comment by gogbajbobo** [comment]
У юзера не могла быть такая большая задержка из-за того, что по умолчанию геотрекинг выключен, соответственно запрос на включение геолокации не показывается, статус — notDetermined.
И только после того, как он получил настройки, где говорится, что надо запускать геотрекинг, его и спросили включать или нет. И вот всё это время пока настройки не пришли клиентДата и была с неопределённым статусом геолокации.
