### ISSUE TITLE
Некорректный тип данных в debt.summ

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#173]
При заведении 8830.14 оно сохраняет и показывает 8830.139999999999 (ios 8)

**Comment by gogbajbobo** [comment]
``` objective-c
NSNumberFormatter *numberFormatter = [[NSNumberFormatter alloc] init];
numberFormatter.numberStyle = NSNumberFormatterDecimalStyle;
numberFormatter.minimumFractionDigits = 2;
numberFormatter.maximumFractionDigits = 2;

NSString *text = @"8840,14";
NSNumber *number = [numberFormatter numberFromString:text];        
NSDecimalNumber *decimalNumber = [NSDecimalNumber decimalNumberWithDecimal:[number decimalValue]];
NSLog(@"text %@, number %@, decimalNumber %@", text, number, decimalNumber);
```

В результате получается:
text 8840,14, number 8840.139999999999, decimalNumber 8840.139999999999

То есть проблема связана не с float/double, а с преобразованием строки в NSNumber.

Простого способа решить проблему не нашёл, пришлось сделать загогулину в коде.

Такой же баг был в процессе ввода суммы долга при сборе долгов, из-за этого могли возникать глюки, так как там получалось, что у долга становился остаток 0.000000000001, при том, что сумму его при сборе указали полностью.
