### ISSUE TITLE
Комментарий к долгу

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#177]
Дать при добавлении долга писать debt.commentText и отобразить его в долгах/кешингах

**Comment by gogbajbobo** [comment]
сделал необязательное поле Комментарий при добавлении долга
в списке долгов должно показываться в конце cell title в скобочках

не очень понимаю как его отображать в кешингах? у кешингов ведь свои комментарии могут быть?

**Comment by alevinru** [comment]
оба комента сцепить можно и чем-то разделить, например, тире или минусом или ::

**Comment by alevinru** [comment]
а, не, коммент кешинга он в верху же, а тут надо где-то в нижней части, где про долг
