### ISSUE TITLE
Проверка времени отключения трекера

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#182]
Нужно вставить в делегат на бекграундФетч

**Comment by alevinru** [comment]
И еще чтобы записывалось в лог про то что включился/выключился трекер

**Comment by gogbajbobo** [comment]
в делегате при бёкграундФетче генерится нотификейшн applicationPerformFetchWithCompletionHandler, который у трекера дёргает checkTimeForTracking, при этом должна и происходить проверка времени вкл/выкл, поэтому немного непонятно, что тут надо сделать?
