### ISSUE TITLE
Каталог товаров

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#188]
Сущности:

Article (name, extraLabel, code, packageRel int, pieceVolume decimal(2), factor int, price decimal(2), articleGroup)

ArticleGroup (name, ord int, articleGroup)

**Comment by alevinru** [comment]
Сервер их отдаст только тому клиенту у которого есть clientData с appVersion >= 55

**Comment by gogbajbobo** [comment]
у ArticleGroup сортировка сначала по ord (asc?), потом по name (acs?)?
а у Article как?

**Comment by alevinru** [comment]
Да, ord asc, name asc. У товаров name asc. Вообще всегда если есть name и нет прочих указаний то по name asc сортировка.
