### ISSUE TITLE
Заказы

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#189]
Сущности:

- Salesman (name) - Менеджер
- SaleOrder - Заказ
 - processing "Статус"
 - date "Дата отгрузки"
 - totalCost decimal(2) "Стоимость"
 - commentText "Комментарий"
 - outlet, salesman
- SaleOrderPosition - Товары Заказа
 - volume "Количество" (штук = бутылок)
 - price0 "Цена"
 - price1 "Цена Бух"
 - article, saleOrder

Сервер их отдает с билда 60

**Comment by alevinru** [comment]
##### price0 - Цена

##### price1 - Цена Бух

Ее нужно показывать только если она не равна price0

##### priceOrigin - Цена базовая (Цена без скидки)

Ее нужно показывать только если она не равна price0 и после нее еще нужно показать процент скидки: round ((priceOrigin - price0)/priceOrigin * 100,1)

**Comment by alevinru** [comment]
Непонятно что делать с полем processing (статус) - там сейчас строковые коды состояния заказа:

Код | Расшифровка
------ | --------------------- 
processed | Проведен
canceled | Отменен
deleted | Удален
processing | Передается в 1С
processing.upload | Передается в систему
processing.onhold | Заблокирован клиент
draft | Черновик
draft.unlock | Черновик
draft.fromhold | Черновик
draft.lowcredit | Отказ по лимиту
draft.lowsumm | Отказ по сумме
draft.noremains | Нет остатков
rejected | Отказ проведения в 1С
done | Передан в 1С

Список может дополняться в будущем. Наверное, нужно сущность завести отдальную?

**Comment by gogbajbobo** [comment]
Ну да, наверно имеет смысл сделать processing отдельной сущностью.
SaleOrderProcessing (status) — как-то так?
Или Processing — это может быть какая-то более общая сущность, не только про заказы?

**Comment by gogbajbobo** [comment]
У SaleOrder поле commentText — это же родительское поле STMComment'а?

**Comment by gogbajbobo** [comment]
У SaleOrderPosition поля volume, price0 и price1 — decimal(2)?

**Comment by gogbajbobo** [comment]
priceOrigin — это к SaleOrderPosition относится?
volume — это что, общий литраж по данной позиции? Это он вместо количества штук используется?

**Comment by gogbajbobo** [comment]
Там еще надо поле cost0 и cost1 завести, в нем volume*price0 с округлением до 2х знаков.
Еще надо будет сделать поля volume1 и volume0.

**Comment by gogbajbobo** [comment]
@alevinru, упомянутые выше (cost0 и cost1) и (volume1 и volume0) как-то связаны с #200 и #201 ?

**Comment by alevinru** [comment]
Не, это совсем отдельная тема, пока без нее можно вполне
