### ISSUE TITLE
ASIdentifierManager.advertisingIdentifier

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#195]
Нужно попробовать в качестве идетификатора устройства

**Comment by gogbajbobo** [comment]
Отдельное свойство завести у clientData или так же в deviceUUID писать?
Если в отдельное поле не делать, то привязка к юзерам поломается же?

**Comment by alevinru** [comment]
Пиши в deviceUUID и в хедере запросов его тоже, я пока не делал привязку
