### ISSUE TITLE
Обновление одной сущности

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#196]
Хочется в пуше прислать имя сущности и чтобы оно только ее скачало

**Comment by gogbajbobo** [comment]
В пуш-нотификаторе в разделе remoteControl надо вызвать у STMSyncer метод "receiveEntities:", в аргументе передать массив имён сущностей:
```json
"remoteCommands":
{
	"STMSyncer":
	{
		"receiveEntities:":
		[
		 "STMSetting",
		 "STMSalesman",
		 "STMOutlet"
		]
	}
}
```

**Comment by gogbajbobo** [comment]
Имена сущностей теперь принимаются без "STM".
