### ISSUE TITLE
Цены и ТипыЦен

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#200]
##### Сущности:

- PriceType (name)
- Price (price decimal(2), article, priceType)

Сервер отдает их с билда 70

Потом, наверное, нужно будет убрать поле Article.price, но пока пусть остается

##### В Каталоге:

- Нужно показать поповер-выбор ТипаЦен
- Запомнить выбор в юзердефолтсах
- Цены в ячейке товара показывать из Price выбранного типа
- Товары и Категории показывать только те, где есть цена выбранного типа

**Comment by alevinru** [comment]
Считаем что "есть цена" если она больше 0

**Comment by gogbajbobo** [comment]
А в поповере, где инфа по артиклу, там какую цену показывать? Выбранного типа или все какие есть?

**Comment by alevinru** [comment]
Покажи какие есть

**Comment by alevinru** [comment]
Хотя это не принципиально, сделай как тебе проще
