### ISSUE TITLE
Остатки

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#201]
##### Сущности:

- Stock (volume int, displayVolume string, article)
 - volume: остаток штук (бутылок) - его нельзя показывать
 - displayVolume: остаток в штуках или днях - его нужно показывать

Сервер отдает это с билда 70

**Comment by alevinru** [comment]
volume может быть равно 0 - это значит остатка нет

**Comment by gogbajbobo** [comment]
Stock он один у позиции или много складов может быть? Article - Stock один-к-одному или один-ко-многим?

**Comment by gogbajbobo** [comment]
А если у склада сделать поле локейшн, то можно на карте показывать сколько на каком складе осталось.

**Comment by alevinru** [comment]
Article-Stock один-к-одному-или-нулю пока, так как склад пока один. Stock это не склад, а запас. Склад будет Warehouse и тогда сделаем Stock.warehouse

**Comment by gogbajbobo** [comment]
Сделать у Stock поле storeHouse и сущность StoreHouse с адресом и координатами. И показывать потом маршруты доставки товаров.

**Comment by alevinru** [comment]
Не, не надо пока мудрить. Маршруты от склада не нужны пока никому, так как мы не тех кто развозит заказы обслуживаем, а тех, кто заказы собирает.
