### ISSUE TITLE
Внутренняя реклама

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#211]
Хотят чтобы несколько раз в день пользователю показывалась картинка с 1-2 абзацами текста.

Наверное, нужно так: к имеющимся сообщениям добавить необязательные поля:
- img - ссылка на jpg или png картинку, например: https://s3-eu-west-1.amazonaws.com/gkgradus/etc/2015-04-marketing-01.jpg
- schedule - расписание показа, например (mon,tue,wed,thu,fri)@(12,14,16)

**Comment by gogbajbobo** [comment]
Эти поля — это поля у сущности STMMessage?

**Comment by alevinru** [comment]
Ага

**Comment by gogbajbobo** [comment]
Я вот думаю, может вместо поля img присылать картинку как STMMessagePicture (подкласс STMPicture), которая будет связана уже с STMMessage? Там и поле href есть и методы у меня для получения картинок и записи их в память готовые уже есть.

**Comment by alevinru** [comment]
Давай так, да, тогда может сделаем их несколько чтоб можно было у одного месаджа?

**Comment by gogbajbobo** [comment]
Несколько если, то непонятно тогда как и где их показывать надо будет. Хотя можно сделать, чтобы было несколько, а для начала я буду только одну показывать.

**Comment by gogbajbobo** [comment]
Добавил в модели данных к STMMessage поле schedule (string) и связь-ко-многим pictures (STMMessagePicture).

**Comment by gogbajbobo** [comment]
Если возможно, то schedule наверно лучше присылать так, чтобы дни недели были цифрами: «The weekday units are the numbers 1 through N (where for the Gregorian calendar N=7 and 1 is Sunday)». Хотя это не критично.

**Comment by alevinru** [comment]
schedule мне вообще все-равно как кодировать, как там в рос роднее так и надо сделать
