### ISSUE TITLE
По запросу отправлять на сервер информацию об объекте

### ISSUE THREAD

**Issue by alevinru** [Sistemium/iSistemium#215]
В целях диагностики, например, по пуш-уведомлению со неким пейлоадом содержащим xid интересующего объекта писать его состояние в виде джсон в лог с типом important

**Comment by gogbajbobo** [comment]
Предлагаю пейлоад такого типа:
requestInfo: "970cbf20-8e09-4640-a7d0-7700e25e27f2"

**Comment by gogbajbobo** [comment]
А ты же будешь хотеть в одном пуш-уведомлении слать и запрос на инфу об объекте и задание синкеру на аплоад, и может быть что-то ещё?

**Comment by alevinru** [comment]
Ну, теоретически да, а так ваще можно и не смешивать все в кучу

**Comment by alevinru** [comment]
ну ваще конечно лучше это requestInfo куда-то спрятать на уровень ниже, типа это же аргумент какой-то функции приложения, может ее даже в отдельный класс выпилить и тогда в корне пейлоада будет этот класс, как и для синкеров-трекеров ща

**Comment by alevinru** [comment]
Типа STMRemoteController

**Comment by gogbajbobo** [comment]
Для трекера там сейчас приходит имя класса и start/stop. А для синкера, судя по коду, приходит syncer: "upload". Надо может всё привести к какому-то общему знаменателю? Например всегда указывать имя класса и метод, который в нём надо дёрнуть.
Как-то так может:
```json
[
    {
    "STMLocationTracker": "startTracking",
    "STMBatteryTracker": "stopTracking",
    "STMSyncer": "upload",
    "STMObjectController": 
        {
        "requestInfo": "970cbf20-8e09-4640-a7d0-7700e25e27f2"
        }
    }
]
```

А парсинг етого запроса я уже сделаю внутри STMRemoteController.

**Comment by alevinru** [comment]
Если класс и метод указывать, то тогда уж и параметры надо именованные:
````
[
    {
    "STMObjectController": 
        {
        "requestInfo": {"xid": "970cbf20-8e09-4640-a7d0-7700e25e27f2"}
        }
    }
]
````

 Хотя для методов с одним аргументом можно договориться об упрощенной записи, т.е. "имяМетода": "значениеАргумента"

**Comment by gogbajbobo** [comment]
Мне кажется нету смысла указывать имя параметра, потому как я могу только один объект типа id передать в метод: https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/#//apple_ref/occ/instm/NSObject/performSelector:withObject:afterDelay:

Хотя можно и словарь передавать, если метод уже будет знать, что с ним там делать.

**Comment by gogbajbobo** [comment]
Ещё было бы удобно, если бы этот словарь с классами и методами был бы тоже внутри отдельного словаря, чтобы мне на этапе получения нотификейшна сразу откусывать команды на управления от всего пейлоада:

```json
{
	"aps":
	{
		"alert": "Alert text",
		"badge": 1
	},
	"remoteCommands":
	{
		"STMLocationTracker": "startTracking",
		"STMBatteryTracker": "stopTracking",
		"STMSyncer": "upload",
		"STMObjectController": 
		{
			"requestInfo": "970cbf20-8e09-4640-a7d0-7700e25e27f2"
		}
	}
}
```

**Comment by alevinru** [comment]
Можно так, да

**Comment by gogbajbobo** [comment]
Прога принимает json следующего вида:

```json
{
	"aps":
	{
		"alert": "Alert text",
		"badge": 1
	},
	"remoteCommands":
	{
		"STMLocationTracker": "startTracking",
		"STMBatteryTracker": "stopTracking",
		"STMSyncer": "upload",
		"STMLogger": 
		{
			"requestInfo:": "970cbf20-8e09-4640-a7d0-7700e25e27f2",
			"someOtherMethod": ""
		}
	}
}
```

Методы, которым передаётся аргумент, пишутся с ":" в конце (см. "requestInfo:"). Если в том же списке надо вызвать метод без аргументов, то пишется имя метода без двоеточия и пустая строка (см. "someOhterMethod").

Можно вызвать практически любой метод класса без предварительной подготовки, за исключением методов внутри которых есть цикл for(), почему-то это приводит к падению проги, причину пока не понял.

Если нужно вызвать метод какого-либо инстанса, то нужно в коде STMRemoteController.m прописать какой инстанс какому классу соответствует.

Пока для совместимости оставил поддержку старого способа обработки нотификешнов.

**Comment by gogbajbobo** [comment]
Замена imp(receiver, selector, object) на [receiver performSelector:selector withObject:object afterDelay:0] лечит падение проги на методах с циклом for() — https://github.com/Sistemium/iSistemium/commit/900781a4abb828f4d1d8e2b02a83c581e048ebcd.
